// A API substituirá/atualizará esta lista futuramente.
// Nunca coloque chaves ou senhas neste arquivo público.
export const produtos = [
  {
    id: "hotmart-1709940",
    nome: "21 Métodos Naturais para Ansiedade",
    descricao: "Curso digital com práticas apresentadas pelo produtor para bem-estar e manejo cotidiano da ansiedade.",
    categoria: "cursos",
    loja: "Hotmart",
    preco: null,
    precoAnterior: null,
    link: "https://go.hotmart.com/D66878245U",
    selo: "Link verificado",
    icone: "🎓",
    cor: "azul",
    destaque: true,
    demonstracao: false,
    ativo: true,
  },
  {
    id: "smartphone-demo",
    nome: "Smartphone 5G 256 GB",
    descricao: "Espaço reservado para ofertas de Amazon, Magalu e outras lojas após a conexão das APIs.",
    categoria: "eletronicos",
    loja: "Comparação em breve",
    preco: 1899.9,
    precoAnterior: 2299.9,
    link: "#",
    selo: "Demonstração",
    icone: "📱",
    cor: "roxo",
    destaque: true,
    demonstracao: true,
    ativo: true,
  },
  {
    id: "airfryer-demo",
    nome: "Air Fryer 5 litros",
    descricao: "Modelo de card pronto para receber preço, foto e link de afiliado automaticamente.",
    categoria: "casa",
    loja: "Comparação em breve",
    preco: 349.9,
    precoAnterior: 499.9,
    link: "#",
    selo: "Demonstração",
    icone: "🍟",
    cor: "laranja",
    destaque: true,
    demonstracao: true,
    ativo: true,
  },
  {
    id: "notebook-demo",
    nome: "Notebook 15,6 polegadas",
    descricao: "Exemplo visual para a futura comparação de preços entre diferentes lojas parceiras.",
    categoria: "eletronicos",
    loja: "Comparação em breve",
    preco: 2899.9,
    precoAnterior: 3399.9,
    link: "#",
    selo: "Demonstração",
    icone: "💻",
    cor: "verde",
    destaque: false,
    demonstracao: true,
    ativo: true,
  },
  {
    id: "passagem-demo",
    nome: "Ofertas de passagens aéreas",
    descricao: "Área preparada para receber um parceiro de viagens e pesquisar destinos e datas.",
    categoria: "viagens",
    loja: "Parceiro em definição",
    preco: null,
    precoAnterior: null,
    link: "#",
    selo: "Em preparação",
    icone: "✈️",
    cor: "ceu",
    destaque: false,
    demonstracao: true,
    ativo: true,
  },
];
